// tslint:disable
/**
 * 商户侧
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { PaymentToken } from "./PaymentToken";

/**
 * LINK
 * @export
 * @interface Link
 */
export interface Link {
    /**
     * ID
     * @type {string}
     * @memberof Link
     */
    id?: string;
    /**
     * 外部ID，唯一
     * @type {string}
     * @memberof Link
     */
    externalId?: string;
    /**
     * 乐观锁
     * @type {number}
     * @memberof Link
     */
    revision?: number;
    /**
     * 创建人
     * @type {string}
     * @memberof Link
     */
    createdBy?: string;
    /**
     *
     * @type {string}
     * @memberof Link
     */
    createdTime?: string;
    /**
     * 更新人
     * @type {string}
     * @memberof Link
     */
    updatedBy?: string;
    /**
     *
     * @type {string}
     * @memberof Link
     */
    updatedTime?: string;
    /**
     * 1 付款链接 2 捐款链接 3小费链接
     * @type {number}
     * @memberof Link
     */
    type?: number;
    /**
     * 名称或为啥付费
     * @type {string}
     * @memberof Link
     */
    name?: string;
    /**
     * 图片url
     * @type {string}
     * @memberof Link
     */
    images?: string;
    /**
     * 描述
     * @type {string}
     * @memberof Link
     */
    description?: string;
    /**
     * 价格类型  1货币计价 2 按代币计价
     * @type {number}
     * @memberof Link
     */
    priceType?: number;
    /**
     * 货币类型
     * @type {string}
     * @memberof Link
     */
    currencyType?: string;
    /**
     * 货币金额
     * @type {number}
     * @memberof Link
     */
    currencyPrice?: number;
    /**
     * 显示货币
     * @type {string}
     * @memberof Link
     */
    displayedCurrent?: string;
    /**
     * 收款代币
     * @type {Array<PaymentToken>}
     * @memberof Link
     */
    paymentTokens?: Array<PaymentToken>;
    /**
     * 主颜色
     * @type {string}
     * @memberof Link
     */
    primaryColor?: string;
    /**
     * 二维码颜色
     * @type {string}
     * @memberof Link
     */
    qrCrodColor?: string;
    /**
     * 是否需要名称 1是 默认0否
     * @type {number}
     * @memberof Link
     */
    collectNameStatus?: number;
    /**
     * 是否需要邮箱 1是 默认0否
     * @type {number}
     * @memberof Link
     */
    collectEmailStatus?: number;
    /**
     * 是否需要账单地址 1是 默认0否
     * @type {number}
     * @memberof Link
     */
    collectBilingAddressStatus?: number;
    /**
     * 是否需要送货地址 1是 默认0否
     * @type {number}
     * @memberof Link
     */
    collectShippingAddressStatus?: number;
    /**
     * 是否需要国家/地区 1是 默认0否
     * @type {number}
     * @memberof Link
     */
    collectCountryStatus?: number;
    /**
     * 是否需要数量 1是 默认0否
     * @type {number}
     * @memberof Link
     */
    collectQuantityStatus?: number;
    /**
     * 自定义字段
     * @type {string}
     * @memberof Link
     */
    collectOtherData?: string;
    /**
     * 是否开锁 1是
     * @type {number}
     * @memberof Link
     */
    unlockStauts?: number;
    /**
     * 下载链接
     * @type {string}
     * @memberof Link
     */
    downloadUrl?: string;
    /**
     * 1显示确定  2将用户重定向到另外一个网站
     * @type {number}
     * @memberof Link
     */
    afterStatus?: number;
    /**
     * 网站地址
     * @type {string}
     * @memberof Link
     */
    website?: string;
    /**
     * 是发送邮件到我的账户1是
     * @type {number}
     * @memberof Link
     */
    emailStatus?: number;
    /**
     * 是否发送回调  1是 0否
     * @type {number}
     * @memberof Link
     */
    callbackStatus?: number;
    /**
     * 回调终端
     * @type {string}
     * @memberof Link
     */
    callbackEndpoint?: string;
    /**
     * 折扣参数json
     * @type {string}
     * @memberof Link
     */
    discountParams?: string;
    /**
     *
     * @type {string}
     * @memberof Link
     */
    startDate?: string;
    /**
     *
     * @type {string}
     * @memberof Link
     */
    endDate?: string;
    /**
     * 限制数量
     * @type {string}
     * @memberof Link
     */
    limitQuantity?: string;
    /**
     * 货币类型
     * @type {string}
     * @memberof Link
     */
    amountCurrency?: string;
    /**
     * 第1个建议价格
     * @type {number}
     * @memberof Link
     */
    suggestion1?: number;
    /**
     * 第2个建议价格
     * @type {number}
     * @memberof Link
     */
    suggestion2?: number;
    /**
     * 第3个建议价格
     * @type {number}
     * @memberof Link
     */
    suggestion3?: number;
    /**
     * 账户id
     * @type {string}
     * @memberof Link
     */
    accountId?: string;
}
