// tslint:disable
/**
 * 商户侧
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 收款代币
 * @export
 * @interface PaymentToken
 */
export interface PaymentToken {
    /**
     * 链
     * @type {string}
     * @memberof PaymentToken
     */
    blockchain?: string;
    /**
     * 代币名称
     * @type {string}
     * @memberof PaymentToken
     */
    name?: string;
    /**
     * 代币缩写
     * @type {string}
     * @memberof PaymentToken
     */
    symbol?: string;
    /**
     * 代币地址
     * @type {string}
     * @memberof PaymentToken
     */
    tokenAddress?: string;
    /**
     * 代币logo
     * @type {string}
     * @memberof PaymentToken
     */
    logo?: string;
    /**
     * 代币精度
     * @type {string}
     * @memberof PaymentToken
     */
    decimals?: string;
    /**
     * 是否可兑换
     * @type {boolean}
     * @memberof PaymentToken
     */
    routable?: boolean;
    /**
     * 收款地址
     * @type {string}
     * @memberof PaymentToken
     */
    receiveAddress?: string;
    /**
     * 币种金额(如果使用货币计价，则需要在用户支付时实时进行汇率换算)
     * @type {number}
     * @memberof PaymentToken
     */
    amount?: number;
}
