// tslint:disable
/**
 * 商户侧
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { PaymentToken } from "./PaymentToken";

/**
 * 支付请求链接
 * @export
 * @interface Request
 */
export interface Request {
    /**
     * ID
     * @type {string}
     * @memberof Request
     */
    id?: string;
    /**
     * 账户id
     * @type {string}
     * @memberof Request
     */
    accountId?: string;
    /**
     * 价格类型  1货币计价 2 按代币计价
     * @type {number}
     * @memberof Request
     */
    priceType: number;
    /**
     * 货币类型
     * @type {string}
     * @memberof Request
     */
    currencyType?: string;
    /**
     * 货币金额
     * @type {number}
     * @memberof Request
     */
    currencyPrice?: number;
    /**
     * 显示货币
     * @type {string}
     * @memberof Request
     */
    displayedCurrency?: string;
    /**
     *
     * @type {string}
     * @memberof Request
     */
    dueDate?: string;
    /**
     * 付款目的
     * @type {string}
     * @memberof Request
     */
    service?: string;
    /**
     * 付款人
     * @type {string}
     * @memberof Request
     */
    payer?: string;
    /**
     * 交付类型 1邮件 2自己交付
     * @type {number}
     * @memberof Request
     */
    deliveryType: number;
    /**
     * 交付邮箱
     * @type {string}
     * @memberof Request
     */
    deliveryEmail?: string;
    /**
     *
     * @type {string}
     * @memberof Request
     */
    deliveryTime?: string;
    /**
     * 收款代币
     * @type {Array<PaymentToken>}
     * @memberof Request
     */
    tokens?: Array<PaymentToken>;
    /**
     * 创建人
     * @type {string}
     * @memberof Request
     */
    createdBy?: string;
    /**
     *
     * @type {string}
     * @memberof Request
     */
    createdTime?: string;
    /**
     * 更新人
     * @type {string}
     * @memberof Request
     */
    updatedBy?: string;
    /**
     *
     * @type {string}
     * @memberof Request
     */
    updatedTime?: string;
}
